import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Head from 'next/head';
import { getCssText } from '@/stitches.config';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
    <Head>
      <style id='stitches' dangerouslySetInnerHTML={{ __html: getCssText() }} />
    </Head>
    <body className={inter.className}>{children}</body>
    </html>
  );
}

export const dynamic = 'error';
